import { Router } from "express";
import { authorizedRequest, checkCode, clearNotificationRequest, confirmRequest, deleteAccount, deleteRequest, getAllbarber, getAllClients, getAllConfirmedRequest, getAllConfirmedRequestByUserId, getAllConfirmedRequestItsComplete, getAllRequest, getAllRequestByBarberId, getAllRequestById, getAllRequestProduct, getOrdersByDeviceId, getUserById, iamHereRequest, inTrafficRequest, isItCompleteRequest, lockAndUnlockUser, login, pushNotification, register, resetTimetable, sendCustomNotification, sendRequestProduct, sendRequestToAdmin, socialLogin, updateAddress, updateLocationUser, updateUser, updateUserAvatars } from "../controllers";
import { forgotPassword } from "../controllers/user/forgotPassword";
import { resetPassword } from "../controllers/user/resetPassword";
import { confirmRequestProduct } from "../controllers/user/confirmRequestProduct";
const router = Router();

router.post("/client-register", register);
router.post("/login", login);
router.post("/check-code", checkCode);
router.post("/social-login", socialLogin);
router.post("/register-token-push-notification/:userId", pushNotification);
router.post("/send-request-to-admin", sendRequestToAdmin);
router.post("/send-request-to-product", sendRequestProduct);
router.put("/confirm-request-products/:requestId", confirmRequestProduct);
router.get("/all-request-product", getAllRequestProduct);
router.get("/get-info/:id", getUserById);
router.get("/orders/device/:deviceId", getOrdersByDeviceId);
router.post("/notifications/custom", sendCustomNotification);
router.put("/update-profile", updateUser);
router.delete("/delete-user/:id", deleteAccount);
router.put("/client/update-address/:id", updateAddress);

router.put("/forgot-password", forgotPassword);
router.put("/reset-password", resetPassword);
router.put("/reset-time", resetTimetable);
router.put("/update-user-avatars", updateUserAvatars);
router.put("/lock-and-unlock-user/:id", lockAndUnlockUser);
router.put("/confirm-request/:requestId", confirmRequest);
router.put("/authorize-request/:requestId", authorizedRequest);
router.put("/user-update-location/:id", updateLocationUser);
router.put("/in-traffic/:requestId", inTrafficRequest);
router.put("/is-it-complete/:requestId", isItCompleteRequest);
router.put("/i-am-here/:requestId", iamHereRequest);
router.put("/clear-request/:requestId", clearNotificationRequest);
router.get("/get-all-request/:baberId", getAllRequestByBarberId);
router.get("/get-all-request-by-id/:id", getAllRequestById);
router.get("/all-barber", getAllbarber);
router.get("/all-clients", getAllClients);
router.get("/all-request", getAllRequest);
router.get("/all-complet-request/:userId", getAllConfirmedRequestItsComplete);
router.get("/all-confirmed-request", getAllConfirmedRequest);
router.get("/all-confirmed-request/:userId", getAllConfirmedRequestByUserId);
router.delete("/delete-request/:requestId", deleteRequest);

export default router;